### ISSUE TITLE
Add new component presets for navbars

### ISSUE THREAD

**Issue by JoscelynJames** [mui-storyblok/mui-storyblok#136]
**Is your feature request related to a problem? Please describe.**
Building out a full-page website with `mui-storyblok` can be time-consuming. In order to streamline the process, we should add presets for some basic components. 

**Describe the solution you'd like**
Add navbar presets. This could include but is not limited to:
1. Top navbar with a collapsable side nav
2. Top navbar with links and a logo
3. Top navbar with dropdown menus for navigation

**Current Blockers**
- [x] Research different types of navbars we want to add
- [x] Design navbars (link to them in this issue)

**Comment by apjames93** [comment]
nav bar presets in the newest version of mui-storyblok
