### ISSUE TITLE
Add new component presets for cards

### ISSUE THREAD

**Issue by JoscelynJames** [mui-storyblok/mui-storyblok#137]
**Is your feature request related to a problem? Please describe.**
Building out a full-page website with `mui-storyblok` can be time-consuming. In order to streamline the process, we should add presets for some basic components. 

**Describe the solution you'd like**
Add card presets. This could include but is not limited to:
1. Simple media card with image, title, and paragraph
2. Complex media card with image, title, paragraph, and links 

**Current Blockers**
- [x] Research different types of cards we want to add. We can check out [mui-exmaples](https://material-ui.com/components/cards)
- [x] Design cards (link to them in this issue)

**Comment by apjames93** [comment]
Added in mui-treasury cards and presets for the mui card  in 2.0.0
