### ISSUE TITLE
Add new component presets for lists

### ISSUE THREAD

**Issue by JoscelynJames** [mui-storyblok/mui-storyblok#138]
**Is your feature request related to a problem? Please describe.**
Building out a full-page website with `mui-storyblok` can be time-consuming. In order to streamline the process, we should add presets for some basic components. 

**Describe the solution you'd like**
Add list presets. This could include but is not limited to:
1. List with icons
2. List with checkboxes
3. List with image
4. Nested lists

**Current Blockers**
- [x] Research different types of lists we want to add. 
- [x] Design lists (link to them in this issue)

**Comment by apjames93** [comment]
Presets added and new list added from mui-treasury
