### ISSUE TITLE
Add new component presets for dialogs

### ISSUE THREAD

**Issue by JoscelynJames** [mui-storyblok/mui-storyblok#139]
**Is your feature request related to a problem? Please describe.**
Building out a full-page website with `mui-storyblok` can be time-consuming. In order to streamline the process, we should add presets for some basic components. 

**Describe the solution you'd like**
Add dialog presets. This could include but is not limited to:
1. Form dialog that submits
2. Simple warning dialog 

**Current Blockers**
- [x] Research different types of dialog we want to add. 
- [x] Design dialog (link to them in this issue)

**Comment by apjames93** [comment]
added in 2.0.0
