### ISSUE TITLE
Add a demo page for a marketing site

### ISSUE THREAD

**Issue by JoscelynJames** [mui-storyblok/mui-storyblok#141]
**Is your feature request related to a problem? Please describe.**
Building out a full-page website with `mui-storyblok` can be time-consuming. In order to streamline the process, we should add some pages that can help people get up and going really fast.

**Describe the solution you'd like**
Add a page that could work as a marketing website for any content

**Current Blockers**
- [x] Design marketing page (link to them in this issue)

**Comment by apjames93** [comment]
added presets to the page to select from in 2.0.0 will have to run `npx migrate-storyblok-presets` cmd to add in presets to storyblok space
