### ISSUE TITLE
Update how transitions are implemented  

### ISSUE THREAD

**Issue by JoscelynJames** [mui-storyblok/mui-storyblok#142]
**Is your feature request related to a problem? Please describe.**
Currently, transitions are sequential and are hard to configure. We should update how we can implement transitions to make them more flexible

**Describe the solution you'd like**
We could move to be a default on a component but let the user choose if they need a transition. This would allow for more control and customization.

**Comment by apjames93** [comment]
we added transitions on each grid and gridItem in the editor with a single select. they proc when they are in view on the DOM
